
export const TOTAL_QUESTIONS = 10;
export const BOSTON_QUESTIONS_COUNT = 3;
export const GENERAL_QUESTIONS_COUNT = TOTAL_QUESTIONS - BOSTON_QUESTIONS_COUNT;
export const ANSWER_TIMEOUT_SECONDS = 15;
