import { Question, QuestionType } from '../types';
import { BOSTON_QUESTIONS_COUNT, GENERAL_QUESTIONS_COUNT } from '../constants';

const generalQuestions: Question[] = [
    // 재구성된 카테고리: 지남력, 기억력, 주의집중 및 계산, 언어 기능, 집행 기능
    // 지남력 (Orientation)
    { id: 5, type: QuestionType.GENERAL, category: '지남력', text: '오늘은 몇 월 며칠인가요?', correctAnswer: '오늘 날짜' },
    { id: 11, type: QuestionType.GENERAL, category: '지남력', text: '지금 있는 이곳은 어디인가요? (예: 집, 병원, 공원)', correctAnswer: '현재 장소' },
    { id: 12, type: QuestionType.GENERAL, category: '지남력', text: '올해는 몇 년도인가요?', correctAnswer: '현재 연도' },
    { id: 23, type: QuestionType.GENERAL, category: '지남력', text: '어제가 무슨 요일이었나요?', correctAnswer: '어제 요일' },
    { id: 26, type: QuestionType.GENERAL, category: '지남력', text: '지금은 어떤 계절인가요?', correctAnswer: '현재 계절' },
    { id: 44, type: QuestionType.GENERAL, category: '지남력', text: '지금으로부터 3일 전은 무슨 요일이었나요?', correctAnswer: '3일 전 요일' },
    { id: 91, type: QuestionType.GENERAL, category: '지남력', text: '오늘은 무슨 요일인가요?', correctAnswer: '오늘 요일' },
    { id: 92, type: QuestionType.GENERAL, category: '지남력', text: '지금 대략 몇 시쯤 되었나요?', correctAnswer: '현재 시간' },
    { id: 94, type: QuestionType.GENERAL, category: '지남력', text: '지금 계절에 입는 옷차림은 어떤 것이 있을까요?', correctAnswer: '현재 계절 옷차림' },
    { id: 95, type: QuestionType.GENERAL, category: '지남력', text: '현재 거주하고 있는 도시의 이름은 무엇인가요?', correctAnswer: '거주 도시' },
    { id: 96, type: QuestionType.GENERAL, category: '지남력', text: '아침, 점심, 저녁 중 지금은 언제를 지나고 있나요?', correctAnswer: '현재 시간대' },
    { id: 100, type: QuestionType.GENERAL, category: '지남력', text: '지금 창 밖은 밝은가요, 어두운가요?', correctAnswer: '현재 시간대' },

    // 기억력 (Memory)
    { id: 1, type: QuestionType.GENERAL, category: '기억력', text: '방금 제가 말한 세 가지 단어를 기억했다가 다시 말해보세요: 나무, 자동차, 책상.', correctAnswer: '나무, 자동차, 책상' },
    { id: 13, type: QuestionType.GENERAL, category: '기억력', text: '대한민국의 대통령은 누구인가요?', correctAnswer: '현재 대통령 이름' },
    { id: 18, type: QuestionType.GENERAL, category: '기억력', text: '아침 식사로 무엇을 드셨나요?', correctAnswer: '아침 식사 메뉴' },
    { id: 31, type: QuestionType.GENERAL, category: '기억력', text: '조금 전에 제가 드렸던 질문 세 가지를 기억해서 말해보세요.', correctAnswer: '이전 질문 내용' },
    { id: 34, type: QuestionType.GENERAL, category: '기억력', text: '일주일은 총 며칠인가요?', correctAnswer: '7일' },
    { id: 36, type: QuestionType.GENERAL, category: '기억력', text: '광복절은 몇 월 며칠인가요?', correctAnswer: '8월 15일' },
    { id: 38, type: QuestionType.GENERAL, category: '기억력', text: '자동차 바퀴는 보통 몇 개인가요?', correctAnswer: '4개' },
    { id: 41, type: QuestionType.GENERAL, category: '기억력', text: '대한민국의 4대 명절 중 두 가지를 말해보세요.', correctAnswer: '설날, 추석 등' },
    { id: 42, type: QuestionType.GENERAL, category: '기억력', text: '어제 저녁 식사 메뉴는 무엇이었나요?', correctAnswer: '어제 저녁 식사 메뉴' },
    { id: 43, type: QuestionType.GENERAL, category: '기억력', text: '본인의 생년월일을 말씀해주세요.', correctAnswer: '본인 생년월일' },
    { id: 45, type: QuestionType.GENERAL, category: '기억력', text: '가장 최근에 본 영화나 드라마 제목이 무엇인가요?', correctAnswer: '최근 시청 콘텐츠 제목' },
    { id: 48, type: QuestionType.GENERAL, category: '기억력', text: '어릴 적 살던 동네 이름이 기억나시나요?', correctAnswer: '본인의 경험' },
    { id: 49, type: QuestionType.GENERAL, category: '기억력', text: '가장 친한 친구의 이름은 무엇인가요?', correctAnswer: '친구 이름' },
    { id: 50, type: QuestionType.GENERAL, category: '기억력', text: '지갑, 휴대폰, 열쇠. 이 세 가지 단어를 기억했다가 다시 말씀해주세요.', correctAnswer: '지갑, 휴대폰, 열쇠' },
    { id: 70, type: QuestionType.GENERAL, category: '기억력', text: '사계절의 이름을 순서대로 말해보세요.', correctAnswer: '봄, 여름, 가을, 겨울' },
    { id: 93, type: QuestionType.GENERAL, category: '기억력', text: '대한민국의 수도는 어디인가요?', correctAnswer: '서울' },
    { id: 97, type: QuestionType.GENERAL, category: '기억력', text: '우리나라의 가장 큰 명절 두 가지는 무엇인가요?', correctAnswer: '설날, 추석' },
    { id: 98, type: QuestionType.GENERAL, category: '기억력', text: '1년은 총 몇 달인가요?', correctAnswer: '12달' },
    { id: 99, type: QuestionType.GENERAL, category: '기억력', text: '우리나라 국경일 중 하나를 말해보세요.', correctAnswer: '삼일절, 광복절, 개천절, 한글날 등' },
    
    // 주의집중 및 계산 (Attention and Calculation)
    { id: 2, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '100에서 7을 계속 빼보세요. 다섯 번만 계산하면 됩니다.', correctAnswer: '93, 86, 79, 72, 65' },
    { id: 4, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '오백원짜리 빵 두 개와 칠백원짜리 우유 한 개를 사면 총 얼마인가요?', correctAnswer: '천칠백원' },
    { id: 8, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '제가 부르는 숫자를 거꾸로 말해보세요: 3, 8, 5', correctAnswer: '5, 8, 3' },
    { id: 10, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '사과 5개를 샀는데 2개를 먹었습니다. 몇 개가 남았나요?', correctAnswer: '3개' },
    { id: 15, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '한 시간에 60분입니다. 두 시간이면 몇 분인가요?', correctAnswer: '120분' },
    { id: 20, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '천원에서 삼백원을 빼면 얼마인가요?', correctAnswer: '칠백원' },
    { id: 21, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '\'대한민국\'을 거꾸로 말해보세요.', correctAnswer: '국민한대' },
    { id: 25, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '10 더하기 15는 얼마인가요?', correctAnswer: '25' },
    { id: 27, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '제가 부르는 숫자들을 순서대로 따라 말해보세요: 2, 9, 4, 7', correctAnswer: '2, 9, 4, 7' },
    { id: 29, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '네 사람이 사탕을 세 개씩 나누어 가졌습니다. 사탕은 총 몇 개일까요?', correctAnswer: '12개' },
    { id: 33, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '5 곱하기 3은 얼마인가요?', correctAnswer: '15' },
    { id: 39, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '1월부터 5월까지 순서대로 말해보세요.', correctAnswer: '1월, 2월, 3월, 4월, 5월' },
    { id: 46, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '제가 5개의 숫자를 불러드리겠습니다. 잘 듣고 순서대로 따라 말해보세요: 8, 1, 5, 9, 3.', correctAnswer: '8, 1, 5, 9, 3' },
    { id: 51, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '\'사과, 바나나, 포도, 사과, 오렌지\'. 제가 부른 과일 중 \'사과\'는 몇 번 나왔나요?', correctAnswer: '2번' },
    { id: 52, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '제가 \'별\'이라고 말하면 \'달\'이라고 대답해주세요. 별.', correctAnswer: '달' },
    { id: 53, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '요일을 거꾸로 말해보세요. 일요일부터 월요일까지.', correctAnswer: '일, 토, 금, 목, 수, 화, 월' },
    { id: 56, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '1부터 20까지 거꾸로 세어보세요.', correctAnswer: '20, 19, 18...' },
    { id: 57, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '제가 동물 이름을 부르면 \'동물\', 과일 이름을 부르면 \'과일\'이라고 대답하세요. \'호랑이\'.', correctAnswer: '동물' },
    { id: 58, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '제가 동물 이름을 부르면 \'동물\', 과일 이름을 부르면 \'과일\'이라고 대답하세요. \'딸기\'.', correctAnswer: '과일' },
    { id: 59, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '20부터 3씩 빼면서 다섯 번만 말해보세요.', correctAnswer: '17, 14, 11, 8, 5' },
    { id: 60, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '제가 부르는 숫자에 1을 더해서 대답하세요. 5.', correctAnswer: '6' },
    { id: 67, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '\'가나다라마바사\'를 거꾸로 말해보세요.', correctAnswer: '사바마라다나가' },
    { id: 71, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '1,000원짜리 지폐로 150원짜리 껌을 샀습니다. 거스름돈은 얼마일까요?', correctAnswer: '850원' },
    { id: 72, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '한 달에 10만원씩 1년 동안 저금하면 총 얼마가 될까요?', correctAnswer: '120만원' },
    { id: 73, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '사탕 12개를 3명이 똑같이 나누어 가지면 한 사람당 몇 개씩 가질 수 있나요?', correctAnswer: '4개' },
    { id: 74, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '버스 요금이 1,300원입니다. 두 사람이 타려면 얼마를 내야 하나요?', correctAnswer: '2,600원' },
    { id: 75, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '8 더하기 9는 얼마인가요?', correctAnswer: '17' },
    { id: 76, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '20 빼기 6은 얼마인가요?', correctAnswer: '14' },
    { id: 77, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '3 곱하기 7은 얼마인가요?', correctAnswer: '21' },
    { id: 78, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '하루는 24시간입니다. 이틀은 총 몇 시간일까요?', correctAnswer: '48시간' },
    { id: 79, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '축구팀은 11명입니다. 두 팀이 경기를 하면 총 몇 명의 선수가 뛰나요?', correctAnswer: '22명' },
    { id: 80, type: QuestionType.GENERAL, category: '주의집중 및 계산', text: '만 원에서 4,500원을 빼면 얼마인가요?', correctAnswer: '5,500원' },

    // 언어 기능 (Language Function)
    { id: 3, type: QuestionType.GENERAL, category: '언어 기능', text: '시계는 시간을 알려줍니다. 체온계는 무엇을 알려주나요?', correctAnswer: '온도 또는 체온' },
    { id: 9, type: QuestionType.GENERAL, category: '언어 기능', text: '\'사과\'라는 단어로 짧은 문장을 만들어 보세요.', correctAnswer: '문장 만들기' },
    { id: 14, type: QuestionType.GENERAL, category: '언어 기능', text: '과일 종류를 3가지만 말해보세요.', correctAnswer: '과일 이름 3개' },
    { id: 16, type: QuestionType.GENERAL, category: '언어 기능', text: '제가 부르는 단어 를 따라 말해보세요.: 고양이, 강아지, 병아리.', correctAnswer: '고양이, 강아지, 병아리' },
    { id: 19, type: QuestionType.GENERAL, category: '언어 기능', text: '반대말을 말해보세요. \'덥다\'의 반대말은 무엇일까요?', correctAnswer: '춥다' },
    { id: 24, type: QuestionType.GENERAL, category: '언어 기능', text: '비행기는 어디로 다니나요?', correctAnswer: '하늘' },
    { id: 32, type: QuestionType.GENERAL, category: '언어 기능', text: '가위, 바위, 보는 무엇을 할 때 사용하나요?', correctAnswer: '순서나 승패를 정할 때' },
    { id: 37, type: QuestionType.GENERAL, category: '언어 기능', text: '의사와 간호사가 일하는 곳은 주로 어디인가요?', correctAnswer: '병원' },
    { id: 47, type: QuestionType.GENERAL, category: '언어 기능', text: '여름과 관련된 단어를 3가지 말해보세요.', correctAnswer: '예: 바다, 수박, 선풍기' },
    { id: 54, type: QuestionType.GENERAL, category: '언어 기능', text: '\'ㄱ\'으로 시작하는 단어를 아는 대로 5개 말해보세요.', correctAnswer: '예: 가방, 기차, 고양이, 구름, 그림' },
    { id: 55, type: QuestionType.GENERAL, category: '언어 기능', text: '제가 부르는 문장을 따라 말해보세요: \'하늘은 파랗고 구름은 하얗다.\'', correctAnswer: '하늘은 파랗고 구름은 하얗다' },
    { id: 61, type: QuestionType.GENERAL, category: '언어 기능', text: '톱, 망치, 드라이버와 같은 것들을 무엇이라고 부르나요?', correctAnswer: '도구 또는 공구' },
    { id: 63, type: QuestionType.GENERAL, category: '언어 기능', text: '\'크다\'의 비슷한 말을 두 개 이상 말해보세요.', correctAnswer: '거대하다, 넓다, 많다 등' },
    { id: 64, type: QuestionType.GENERAL, category: '언어 기능', text: '다음 단어들을 사용해서 하나의 문장을 만들어 보세요: \'고양이, 의자, 햇빛\'.', correctAnswer: '문장 만들기' },
    { id: 65, type: QuestionType.GENERAL, category: '언어 기능', text: '\'냉장고\'는 무엇을 하는 물건인가요?', correctAnswer: '음식을 차갑게 보관하는 물건' },
    { id: 66, type: QuestionType.GENERAL, category: '언어 기능', text: '\'바다\'하면 떠오르는 것을 3가지 말해보세요.', correctAnswer: '예: 파도, 소금물, 배' },
    { id: 68, type: QuestionType.GENERAL, category: '언어 기능', text: '\'의사\'가 하는 일은 무엇인가요?', correctAnswer: '아픈 사람을 치료하는 일' },

    // 집행 기능 (Executive Function)
    { id: 6, type: QuestionType.GENERAL, category: '집행 기능', text: '\'호랑이도 제 말 하면 온다\'는 속담은 무슨 뜻인가요?', correctAnswer: '어떤 사람에 대해 이야기하고 있는데 그 사람이 마침 나타나는 상황' },
    { id: 7, type: QuestionType.GENERAL, category: '집행 기능', text: '길에 지갑이 떨어져 있다면 어떻게 하시겠어요?', correctAnswer: '주인을 찾아주거나 경찰서에 가져다준다' },
    { id: 17, type: QuestionType.GENERAL, category: '집행 기능', text: '밤에 집에서 연기 냄새가 나면 가장 먼저 무엇을 해야 할까요?', correctAnswer: '불이 났는지 확인하고 119에 신고한다' },
    { id: 22, type: QuestionType.GENERAL, category: '집행 기능', text: '목이 마를 때 가장 먼저 해야 할 일은 무엇일까요?', correctAnswer: '물을 마신다' },
    { id: 28, type: QuestionType.GENERAL, category: '집행 기능', text: '\'물고기\'와 \'새\'의 공통점은 무엇일까요?', correctAnswer: '동물이다' },
    { id: 30, type: QuestionType.GENERAL, category: '집행 기능', text: '약은 왜 의사의 처방에 따라 먹어야 할까요?', correctAnswer: '안전하고 효과적으로 치료하기 위해' },
    { id: 35, type: QuestionType.GENERAL, category: '집행 기능', text: '모르는 사람이 문을 열어달라고 하면 어떻게 해야 하나요?', correctAnswer: '열어주지 않고 부모님이나 어른에게 알린다' },
    { id: 40, type: QuestionType.GENERAL, category: '집행 기능', text: '뜨거운 냄비를 만지기 전에 왜 조심해야 할까요?', correctAnswer: '손을 데일 수 있기 때문에' },
    { id: 62, type: QuestionType.GENERAL, category: '집행 기능', text: '\'티끌 모아 태산\'이라는 속담의 뜻은 무엇인가요?', correctAnswer: '작은 것도 모이면 큰 것이 된다는 뜻' },
    { id: 69, type: QuestionType.GENERAL, category: '집행 기능', text: '다음 중 성격이 다른 하나는 무엇일까요? \'사자, 호랑이, 기린, 독수리\'', correctAnswer: '독수리' },
    { id: 81, type: QuestionType.GENERAL, category: '집행 기능', text: '운전 중에 졸음이 오면 어떻게 해야 할까요?', correctAnswer: '안전한 곳에 차를 세우고 잠시 쉰다' },
    { id: 82, type: QuestionType.GENERAL, category: '집행 기능', text: '친구가 슬퍼 보일 때 어떻게 해주는 것이 좋을까요?', correctAnswer: '위로해주고 이야기를 들어준다' },
    { id: 83, type: QuestionType.GENERAL, category: '집행 기능', text: '요리를 하다가 냄비에 불이 붙었습니다. 가장 먼저 해야 할 일은 무엇일까요?', correctAnswer: '가스 불을 끈다' },
    { id: 84, type: QuestionType.GENERAL, category: '집행 기능', text: '길에서 아픈 사람을 발견하면 어떻게 해야 하나요?', correctAnswer: '119에 신고하고 도움을 요청한다' },
    { id: 85, type: QuestionType.GENERAL, category: '집행 기능', text: '처음 가는 길을 찾아갈 때 가장 도움이 되는 것은 무엇일까요?', correctAnswer: '지도 또는 내비게이션' },
    { id: 86, type: QuestionType.GENERAL, category: '집행 기능', text: '감기에 걸린 것 같을 때 어떻게 해야 하나요?', correctAnswer: '휴식을 취하고 병원에 간다' },
    { id: 87, type: QuestionType.GENERAL, category: '집행 기능', text: '횡단보도를 건널 때 가장 먼저 무엇을 확인해야 하나요?', correctAnswer: '신호등과 좌우를 살핀다' },
    { id: 88, type: QuestionType.GENERAL, category: '집행 기능', text: '낯선 사람이 주는 음료수를 마셔도 될까요?', correctAnswer: '안 된다' },
    { id: 89, type: QuestionType.GENERAL, category: '집행 기능', text: '새 옷을 사기 전에 무엇을 확인해야 할까요?', correctAnswer: '가격, 사이즈, 디자인 등' },
    { id: 90, type: QuestionType.GENERAL, category: '집행 기능', text: '영화관과 같은 공공장소에서 지켜야 할 예절은 무엇이 있을까요?', correctAnswer: '조용히 하고 휴대폰을 끈다' },
];

const bostonNamingQuestions: Question[] = [
    { id: 101, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?bed', correctAnswer: '침대' },
    { id: 102, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?tree', correctAnswer: '나무' },
    { id: 103, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?house', correctAnswer: '집' },
    { id: 104, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?car', correctAnswer: '자동차' },
    { id: 105, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?book', correctAnswer: '책' },
    { id: 106, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?chair', correctAnswer: '의자' },
    { id: 107, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?clock', correctAnswer: '시계' },
    { id: 108, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?flower', correctAnswer: '꽃' },
    { id: 109, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?pencil', correctAnswer: '연필' },
    { id: 110, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?glasses', correctAnswer: '안경' },
    { id: 111, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?key', correctAnswer: '열쇠' },
    { id: 112, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?telephone', correctAnswer: '전화기' },
    { id: 113, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?umbrella', correctAnswer: '우산' },
    { id: 114, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?scissors', correctAnswer: '가위' },
    { id: 115, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?bicycle', correctAnswer: '자전거' },
    { id: 116, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?apple', correctAnswer: '사과' },
    { id: 117, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?banana', correctAnswer: '바나나' },
    { id: 118, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?bus', correctAnswer: '버스' },
    { id: 119, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?comb', correctAnswer: '빗' },
    { id: 120, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?cup', correctAnswer: '컵' },
    { id: 121, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?door', correctAnswer: '문' },
    { id: 122, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?fan', correctAnswer: '선풍기' },
    { id: 123, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?glove', correctAnswer: '장갑' },
    { id: 124, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?hammer', correctAnswer: '망치' },
    { id: 125, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?clothes+iron', correctAnswer: '다리미' },
    { id: 126, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?lamp', correctAnswer: '램프 또는 스탠드' },
    { id: 127, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?moon', correctAnswer: '달' },
    { id: 128, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?needle', correctAnswer: '바늘' },
    { id: 129, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?orange+fruit', correctAnswer: '오렌지' },
    { id: 130, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?piano', correctAnswer: '피아노' },
    { id: 131, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?ring', correctAnswer: '반지' },
    { id: 132, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?sock', correctAnswer: '양말' },
    { id: 133, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?table', correctAnswer: '탁자 또는 테이블' },
    { id: 134, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?toothbrush', correctAnswer: '칫솔' },
    { id: 135, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?violin', correctAnswer: '바이올린' },
    { id: 136, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?wallet', correctAnswer: '지갑' },
    { id: 137, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?window', correctAnswer: '창문' },
    { id: 138, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?airplane', correctAnswer: '비행기' },
    { id: 139, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?ball', correctAnswer: '공' },
    { id: 140, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?bag', correctAnswer: '가방' },
    { id: 141, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?belt', correctAnswer: '벨트' },
    { id: 142, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?boat', correctAnswer: '배' },
    { id: 143, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?bottle', correctAnswer: '병' },
    { id: 144, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?box', correctAnswer: '상자' },
    { id: 145, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?bread', correctAnswer: '빵' },
    { id: 146, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?bridge', correctAnswer: '다리' },
    { id: 147, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?brush', correctAnswer: '붓' },
    { id: 148, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?button', correctAnswer: '단추' },
    { id: 149, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?camera', correctAnswer: '카메라' },
    { id: 150, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?candle', correctAnswer: '양초' },
    { id: 151, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?hat', correctAnswer: '모자' },
    { id: 152, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?cloud', correctAnswer: '구름' },
    { id: 153, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?coin', correctAnswer: '동전' },
    { id: 154, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?computer', correctAnswer: '컴퓨터' },
    { id: 155, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?cow', correctAnswer: '소' },
    { id: 156, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?dog', correctAnswer: '개' },
    { id: 157, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?cat', correctAnswer: '고양이' },
    { id: 158, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?doll', correctAnswer: '인형' },
    { id: 159, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?drum', correctAnswer: '북' },
    { id: 160, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?duck', correctAnswer: '오리' },
    { id: 161, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?elephant', correctAnswer: '코끼리' },
    { id: 162, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?human+eye', correctAnswer: '눈' },
    { id: 163, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?feather', correctAnswer: '깃털' },
    { id: 164, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?finger', correctAnswer: '손가락' },
    { id: 165, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?fish', correctAnswer: '물고기' },
    { id: 166, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?flag', correctAnswer: '깃발' },
    { id: 167, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?fork', correctAnswer: '포크' },
    { id: 168, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?grape', correctAnswer: '포도' },
    { id: 169, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?guitar', correctAnswer: '기타' },
    { id: 170, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?human+hand', correctAnswer: '손' },
    { id: 171, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?heart+shape', correctAnswer: '심장' },
    { id: 172, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?horse', correctAnswer: '말' },
    { id: 173, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?kettle', correctAnswer: '주전자' },
    { id: 174, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?lion', correctAnswer: '사자' },
    { id: 175, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?mirror', correctAnswer: '거울' },
    { id: 176, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?motorcycle', correctAnswer: '오토바이' },
    { id: 177, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?mountain', correctAnswer: '산' },
    { id: 178, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?human+mouth', correctAnswer: '입' },
    { id: 179, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?metal+nail', correctAnswer: '못' },
    { id: 180, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?necklace', correctAnswer: '목걸이' },
    { id: 181, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?onion', correctAnswer: '양파' },
    { id: 182, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?paintbrush', correctAnswer: '페인트붓' },
    { id: 183, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?pants', correctAnswer: '바지' },
    { id: 184, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?paper', correctAnswer: '종이' },
    { id: 185, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?pear', correctAnswer: '배 (과일)' },
    { id: 186, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?pen', correctAnswer: '펜' },
    { id: 187, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?pig', correctAnswer: '돼지' },
    { id: 188, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?pillow', correctAnswer: '베개' },
    { id: 189, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?plate', correctAnswer: '접시' },
    { id: 190, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?potato', correctAnswer: '감자' },
    { id: 191, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?ship', correctAnswer: '배 (선박)' },
    { id: 192, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?shirt', correctAnswer: '셔츠' },
    { id: 193, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?shoes', correctAnswer: '신발' },
    { id: 194, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?spoon', correctAnswer: '숟가락' },
    { id: 195, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?star', correctAnswer: '별' },
    { id: 196, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?strawberry', correctAnswer: '딸기' },
    { id: 197, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?sun', correctAnswer: '해' },
    { id: 198, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?knife', correctAnswer: '칼' },
    { id: 199, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?train', correctAnswer: '기차' },
    { id: 200, type: QuestionType.BOSTON_NAMING, category: '이름대기', text: '이 그림에 있는 것은 무엇입니까?', image: 'https://source.unsplash.com/400x300/?carrot', correctAnswer: '당근' },
];

const shuffleArray = <T,>(array: T[]): T[] => {
    return [...array].sort(() => Math.random() - 0.5);
};

export const getTestQuestions = (): Question[] => {
    const selectedGeneral = shuffleArray(generalQuestions).slice(0, GENERAL_QUESTIONS_COUNT);
    const selectedBoston = shuffleArray(bostonNamingQuestions).slice(0, BOSTON_QUESTIONS_COUNT);
    return shuffleArray([...selectedGeneral, ...selectedBoston]);
};

export const getAllQuestionsForResults = (): Question[] => {
    return [...generalQuestions, ...bostonNamingQuestions];
};